### Suche mit vorhandener Angestellter-ID als admin
GRAPHQL {{graphqlUrl}}
Authorization: Basic {{userAdmin}} {{password}}

{
  angestellter(id: "00000000-0000-0000-0000-000000000001") {
    nachname
  }
}
> {%
    client.test('Query mit ID und admin: OK', () => {
        const status = response.status;
        client.assert(status === 200, `Falscher Statuscode: ${status}`);
    });

    client.test('Query mit ID und admin: application/json', () => {
        const mimeType = response.contentType.mimeType;
        client.assert(mimeType === 'application/json', `Falscher MIME-Typ: ${mimeType}`);
    });

    client.test('Query mit ID und admin: body mit Daten', () => {
        const body = response.body;
        client.assert(typeof body === 'object', `body: ${JSON.stringify(body)}`);
        // TODO Optional Chaining
        const angestellter = body.data.angestellter;
        client.assert(typeof angestellter.nachname === 'string', `angestellter: ${JSON.stringify(body.data.angestellter)}`);
    });
%}

### Suche mit nicht-vorhandener Angestellter-ID als admin
GRAPHQL {{graphqlUrl}}
Authorization: Basic {{userAdmin}} {{password}}

{
  angestellter(id: "ffffffff-ffff-ffff-ffff-ffffffffffff") {
    nachname
  }
}
> {%
    client.test('Query mit nicht-vorhandener ID und admin: OK', () => {
        const status = response.status;
        client.assert(status === 200, `Falscher Statuscode: ${status}`);
    });

    client.test('Query mit nicht-vorhandener ID und admin: application/json', () => {
        const mimeType = response.contentType.mimeType;
        client.assert(mimeType === 'application/json', `Falscher MIME-Typ: ${mimeType}`);
    });

    client.test('Query mit nicht-vorhandener ID und admin: body mit Errors ohne Daten', () => {
        const body = response.body;
        client.assert(typeof body === 'object', `body: ${JSON.stringify(body)}`);
        client.assert(typeof body.data === 'object', `body: ${JSON.stringify(body)}`);
        client.assert(Object.keys(body.data).length === 0, `data: ${JSON.stringify(body.data)}`);
        // TODO Optional Chaining
        const errors = body.errors;
        client.assert(Array.isArray(errors) === true, `errors: ${JSON.stringify(body.errors)}`);
        client.assert(errors.length === 1, `errors: ${JSON.stringify(body.errors)}`);
        client.assert(typeof errors[0].extensions.classification === 'string', `errors: ${JSON.stringify(errors)}`);
        client.assert(errors[0].extensions.classification === 'NOT_FOUND', `errors: ${JSON.stringify(errors)}`);
    });
%}

### Suche mit vorhandener Angestellter-ID als admin
GRAPHQL {{graphqlUrl}}
Authorization: Basic {{userAdmin}} {{password}}

{
  angestellter(id: "00000000-0000-0000-0000-000000000001") {
    nachname
    email
    geburtsdatum
    geschlecht
    familienstand
    adresse {
      plz
      ort
    }
  }
}
> {%
    client.test('Query mit ID und admin: OK', () => {
      const status = response.status;
        client.assert(status === 200, `Falscher Statuscode: ${status}`);
    });

    client.test('Query mit ID und admin: application/json', () => {
        const mimeType = response.contentType.mimeType;
        client.assert(mimeType === 'application/json', `Falscher MIME-Typ: ${mimeType}`);
    });

    client.test('Query mit ID und admin: body mit Daten', () => {
        const body = response.body;
        client.assert(typeof body === 'object', `body: ${JSON.stringify(body)}`);
        // TODO Optional Chaining
        const angestellter = body.data.angestellter;
        client.assert(typeof angestellter.nachname === 'string', `angestellter: ${JSON.stringify(body.data.angestellter)}`);
        client.assert(typeof angestellter.email === 'string', `angestellter: ${JSON.stringify(body.data.angestellter)}`);
    });
%}


### Suche alle Angestellten als admin
GRAPHQL {{graphqlUrl}}
Authorization: Basic {{userAdmin}} {{password}}

{
  angestellte {
    id
    nachname
    kategorie
    hasNewsletter
    geburtsdatum
    homepage
    geschlecht
    familienstand
    interessen
    umsatz {
      betrag
      waehrung
    }
    adresse {
      plz
      ort
    }
  }
}
> {%
    client.test('Query alle Angestellten als admin: OK', () => {
        const status = response.status;
        client.assert(status === 200, `Falscher Statuscode: ${status}`);
    });

    client.test('Query alle Angestellten als admin: application/json', () => {
        const mimeType = response.contentType.mimeType;
        client.assert(mimeType === 'application/json', `Falscher MIME-Typ: ${mimeType}`);
    });

    client.test('Query alle Angestellten als admin: body mit Daten', () => {
        const body = response.body;
        client.assert(typeof body === 'object', `body: ${JSON.stringify(body)}`);
        // TODO Optional Chaining
        const angestellte = body.data.angestellte;
        client.assert(Array.isArray(angestellte) === true, `data: ${JSON.stringify(body.data)}`);
        client.assert(angestellte.length > 0, `data: ${JSON.stringify(body.data)}`);
    });
%}

### Suche Angestellter mit der Emailadresse als admin
GRAPHQL {{graphqlUrl}}
Authorization: Basic {{userAdmin}} {{password}}

{
  angestellte(input: {email: "admin@acme.com"}) {
    id
    nachname
    kategorie
    hasNewsletter
    geburtsdatum
    homepage
    geschlecht
    familienstand
    interessen
    umsatz {
      betrag
      waehrung
    }
    adresse {
      plz
      ort
    }
  }
}
> {%
    client.test('Query mit der Emailadresse als admin: OK', () => {
        const status = response.status;
        client.assert(status === 200, `Falscher Statuscode: ${status}`);
    });

    client.test('Query mit der Emailadresse als admin: application/json', () => {
        const mimeType = response.contentType.mimeType;
        client.assert(mimeType === 'application/json', `Falscher MIME-Typ: ${mimeType}`);
    });

    client.test('Query mit der Emailadresse als admin: body mit Daten', () => {
        const body = response.body;
        client.assert(typeof body === 'object', `body: ${JSON.stringify(body)}`);
        // TODO Optional Chaining
        const angestellte = body.data.angestellte;
        client.assert(Array.isArray(angestellte) === true, `data: ${JSON.stringify(body.data)}`);
        client.assert(angestellte.length === 1, `data: ${JSON.stringify(body.data)}`);
        const angestellter = angestellte[0];
        client.assert(typeof angestellter.nachname === 'string', `angestellter: ${JSON.stringify(angestellter)}`);
    });
%}

### Suche Angestellter mit nicht-vorhandener Emailadresse als admin
GRAPHQL {{graphqlUrl}}
Authorization: Basic {{userAdmin}} {{password}}

{
  angestellte(input: {email: "nicht.vorhanden@acme.com"}) {
    id
  }
}
> {%
    client.test('Query mit nicht-vorhandener Emailadresse und admin: OK', () => {
        const status = response.status;
        client.assert(status === 200, `Falscher Statuscode: ${status}`);
    });

    client.test('Query mit nicht-vorhandener Emailadresse und admin: application/json', () => {
        const mimeType = response.contentType.mimeType;
        client.assert(mimeType === 'application/json', `Falscher MIME-Typ: ${mimeType}`);
    });

    client.test('Query mit nicht-vorhandener Emailadresse und admin: body mit Errors ohne Daten', () => {
        const body = response.body;
        client.assert(typeof body === 'object', `body: ${JSON.stringify(body)}`);
        client.assert(typeof body.data === 'object', `body: ${JSON.stringify(body)}`);
        client.assert(Object.keys(body.data).length === 0, `data: ${JSON.stringify(body.data)}`);
        // TODO Optional Chaining
        const errors = body.errors;
        client.assert(Array.isArray(errors) === true, `errors: ${JSON.stringify(body.errors)}`);
        client.assert(errors.length === 1, `errors: ${JSON.stringify(body.errors)}`);
        client.assert(typeof errors[0].extensions.classification === 'string', `errors: ${JSON.stringify(errors)}`);
        client.assert(errors[0].extensions.classification === 'NOT_FOUND', `errors: ${JSON.stringify(errors)}`);
    });
%}

### Suche Angestellten mit dem Nachnamen als admin
GRAPHQL {{graphqlUrl}}
Authorization: Basic {{userAdmin}} {{password}}

{
  angestellte(input: {nachname: "a"}) {
    id
    nachname
    email
    kategorie
    hasNewsletter
    geburtsdatum
    homepage
    geschlecht
    familienstand
    interessen
    umsatz {
      betrag
      waehrung
    }
    adresse {
      plz
      ort
    }
  }
}
> {%
    client.test('Query mit dem Nachnamen als admin: OK', () => {
        const status = response.status;
        client.assert(status === 200, `Falscher Statuscode: ${status}`);
    });

    client.test('Query mit dem Nachnamen als admin: application/json', () => {
        const mimeType = response.contentType.mimeType;
        client.assert(mimeType === 'application/json', `Falscher MIME-Typ: ${mimeType}`);
    });

    client.test('Query mit dem Nachnamen als admin: body mit Daten', () => {
        const body = response.body;
        client.assert(typeof body === 'object', `body: ${JSON.stringify(body)}`);
        // TODO Optional Chaining
        const angestellte = body.data.angestellte;
        client.assert(Array.isArray(angestellte) === true, `data: ${JSON.stringify(body.data)}`);
        client.assert(angestellte.length > 0, `data: ${JSON.stringify(body.data)}`);
        angestellte.map(angestellter => angestellter.nachname)
            .forEach(nachname => client.assert(nachname.includes('a') || nachname.startsWith('A'), `nachname: ${JSON.stringify(nachname)}`));
    });
%}

### Suche Angestellten mit nicht-vorhandenem Nachnamen als admin
GRAPHQL {{graphqlUrl}}
Authorization: Basic {{userAdmin}} {{password}}

{
  angestellte(input: {nachname: "Nichtvorhanden"}) {
    id
  }
}
